<?php

/**
 * Implements hook_requirements()
 */
function jspdf_requirements($phase) {
  $requirements = array();
  if ($phase == 'runtime') {
    $t = get_t();
    if ($path = libraries_get_path('jspdf')) {
      if (file_exists($path . '/dist/jspdf.source.js')) {
        $requirements['jspdf'] = array(
          'title' => $t('jsPDF'),
          'value' => $t('jspdf.source.js found under !path', array('!path' => $path . '/dist/jspdf.source.js')),
          'severity' => REQUIREMENT_OK,
        );
        return $requirements;
      }
    }
    $requirements['jspdf'] = array(
      'title' => $t('jsPDF'),
      'value' => t('jsPDF library was not found. !download the library and place in under sites/all/libraries/jspdf, so that the library can be found at sites/all/libraries/jspdf/dist/jspdf.source.js.', array('!download' => l(t('Download'), 'https://github.com/MrRio/jsPDF'))),
      'severity' => REQUIREMENT_ERROR,
    );
  }
  return $requirements;
}

/**
 * Implements hook_libraries_info().
 */
function jspdf_libraries_info() {
  $libraries = array();
  $libraries['jspdf'] = array(
    'name' => 'jsPDF',
    'vendor url' => 'http://parall.ax/products/jspdf',
    'download url' => 'https://github.com/MrRio/jsPDF',
    'files' => array(
      'js' => array(
        'dist/jspdf.source.js',
      ),
    ),
    'version arguments' => array(
      'file' => 'dist/jspdf.source.js',
      'pattern' => '/((\d+)\.(\d+)\.(\d+)(rc(\d+)))/',
      'lines' => 4,
    ),    
  );
  return $libraries;
}


